services:
  - type: web
    name: chess-arena
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gthread --threads 4 -w 1 app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
